services:
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "80"]

volumes:
  node_modules: